### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by zry656565** [zry656565/Hit-Kounter#1]
- [ ] 重构
  - [x] 初始版本的代码重构
  - [ ] params 单独提取出来成为一个属性
- [ ] 测试
  - [x] 功能测试
  - [ ] 错误测试
- [ ] 服务器端的错误处理
  - [ ] 缺少参数
  - [ ] 错误的 API
  - [ ] 不存在的 API 版本
- [ ] 浏览器端 JS
  - [ ] **缓存**
  - [x] **对于自动拼接的长度超过 1024 的  `hk.page.get`  请求进行切割**
  - [ ] 错误处理
    - [ ] 超长的请求(1024)
- [x] 实现多种读取数据的方式（标签）
  - [x] 应用于博客
  - [ ] **调整 top area 的样式**
- [x] 部署到 SAE 上，并实现本地测试和 SAE 两套配置的快速切换
- [ ] 文档
  - [ ] tutorial
  - [ ] 简要的 Contribute 指南

**Comment by lozn00** [comment]
不支持相对页面嘛，我用某hexo发现了你们得代码

**Comment by lozn00** [comment]
```
    c = {
        elements: {},
        scan: function() {
            var e = this.elements,
            t = document.querySelectorAll("[data-hk-page]");
            e.current = document.querySelectorAll("[data-hk-page=current]"),
            e.topArea = document.querySelectorAll("[data-hk-top-pages]"),
            e.pages = {};
            for (var n = 0; n < t.length; ++n) {
                var r = t[n].attributes["data-hk-page"].value,
                a = e.pages[r];//不等于就？ t是 pages ,n是当前页面，
                "current" != r && (a ? a.push(t[n]) : e.pages[r] = [t[n]])
            }
        },
```

**Comment by lozn00** [comment]
http://jerryzou.com/posts/introduction-to-hit-kounter-lc/

**Comment by zry656565** [comment]
相关讨论移步：https://github.com/zry656565/Hit-Kounter-LC/issues/3
